# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

# networks:
#   test:
#     name: fabric_test

# services:

#   ca_sro:
#     image: hyperledger/fabric-ca:latest
#     environment:
#       - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
#       - FABRIC_CA_SERVER_CA_NAME=ca-sro
#       - FABRIC_CA_SERVER_TLS_ENABLED=true
#       - FABRIC_CA_SERVER_PORT=7054
#       - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
#     ports:
#       - "7054:7054"
#       - "17054:17054"
#     command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
#     volumes:
#       - ../organizations/fabric-ca/sro:/etc/hyperledger/fabric-ca-server
#     container_name: ca_sro
#     networks:
#       - test

#   ca_revenue:
#     image: hyperledger/fabric-ca:latest
#     environment:
#       - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
#       - FABRIC_CA_SERVER_CA_NAME=ca-revenue
#       - FABRIC_CA_SERVER_TLS_ENABLED=true
#       - FABRIC_CA_SERVER_PORT=8054
#       - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
#     ports:
#       - "8054:8054"
#       - "18054:18054"
#     command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
#     volumes:
#       - ../organizations/fabric-ca/revenue:/etc/hyperledger/fabric-ca-server
#     container_name: ca_revenue
#     networks:
#       - test
#   ca_bank:
#     image: hyperledger/fabric-ca:latest
#     environment:
#       - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
#       - FABRIC_CA_SERVER_CA_NAME=ca-bank
#       - FABRIC_CA_SERVER_TLS_ENABLED=true
#       - FABRIC_CA_SERVER_PORT=6054
#       - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:16054
#     ports:
#       - "6054:6054"
#       - "16054:16054"
#     command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
#     volumes:
#       - ../organizations/fabric-ca/bank:/etc/hyperledger/fabric-ca-server
#     container_name: ca_bank
#     networks:
#       - test

#   ca_orderer:
#     image: hyperledger/fabric-ca:latest
#     environment:
#       - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
#       - FABRIC_CA_SERVER_CA_NAME=ca-orderer
#       - FABRIC_CA_SERVER_TLS_ENABLED=true
#       - FABRIC_CA_SERVER_PORT=9054
#       - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
#     ports:
#       - "9054:9054"
#       - "19054:19054"
#     command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
#     volumes:
#       - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
#     container_name: ca_orderer
#     networks:
#       - test

networks:
  test:
    name: fabric_test
services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:

      LDAP_ORGANISATION: "sro land."
      LDAP_DOMAIN: "land.com"
      LDAP_ADMIN_PASSWORD: "adminpw"
      LDAP_BASE_DN: "dc=land,dc=com"

      LDAP_TLS: "false"

      #LDAP_REPLICATION_CONFIG_SYNCPROV: 'binddn="cn=admin,cn=config" bindmethod=simple credentials="$$LDAP_CONFIG_PASSWORD" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical'
      #LDAP_REPLICATION_DB_SYNCPROV: 'binddn="cn=admin,$$LDAP_BASE_DN" bindmethod=simple credentials="$$LDAP_ADMIN_PASSWORD" searchbase="$$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical'
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    domainname: "land.com"
    hostname: "ldap"
    networks:
      - test
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8090:80"
    networks:
      - test
    depends_on:
      - openldap
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
  # ldaplandcom:
  #   image: osixia/openldap:1.4.0
  #   container_name: openldap
  #   environment:
  #     LDAP_ORGANISATION: "sro land."
  #     LDAP_DOMAIN: "land.com"
  #     LDAP_ADMIN_PASSWORD: "adminpw"
  #     LDAP_BASE_DN: "dc=land,dc=com"
  #     LDAP_TLS: "false"

  #   volumes:
  #    # used to get ldif file into LDAP when adding new user
  #     - /var/lib/ldap
  #     - /etc/ldap/slapd.d
  #     - /container/service/slapd/assets/certs/
  #   ports:
  #    - "389:389"
  #    - "689:689"
  #   domainname: "land.com"
  #   hostname: "ldap"
  #   networks:
  #     - test

  # phpldapadmin:
  #   image: osixia/phpldapadmin:latest
  #   container_name: phpldapadmin
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: "ldap"
  #     PHPLDAPADMIN_HTTPS: "false"
  #   ports:
  #     - "8090:80"
  #   depends_on:
  #     - ldaplandcom

